// <auto-generated />
namespace CommunityNetPortoAngular.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ArticleUpdateTypes_Date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArticleUpdateTypes_Date));
        
        string IMigrationMetadata.Id
        {
            get { return "201612271448182_ArticleUpdateTypes_Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
